export enum ResponseCode {
  Success = 0,
  InternalError = 1,
  InvalidInput = 2,
  UnauthorizedAccess = 3,
  ResourceNotFound = 4,
  DatabaseError = 5,
  ServerTimeout = 6,
  ConnectionFailed = 7,
  DuplicateEntry = 8,
  InsufficientAccess = 9,
  InvalidToken = 10,
  MissingParameters = 11,
  ValidationError = 12,
  ExternalServiceDown = 13,
  NotImplemented = 14,
  AccessDenied = 15,
  FileNotFound = 16,
  InvalidFormat = 17,
  AccountLocked = 18,
  SessionExpired = 19,
  Forbidden = 20,
}
